// Developer Express Code Central Example:
// How to custom draw a crosshair cursor
// 
// This example shows how to provide custom appearance of the crosshair cursor
// using the ChartControl.CustomDrawCrosshair event. This event is invoked when you
// click the Custom Draw Crosshair Cursor button on the form. If you wish to
// display crosshair axis lines and labels on a chart before custom drawing the
// crosshair cursor, set the CrosshairOptions.ShowArgumentLine
// (http://help.devexpress.com/#XtraCharts/DevExpressXtraChartsCrosshairOptions_ShowArgumentLinetopic),
// CrosshairOptions.ShowArgumentLabels
// (http://help.devexpress.com/#XtraCharts/DevExpressXtraChartsCrosshairOptions_ShowArgumentLabelstopic),
// CrosshairOptions.ShowValueLabels
// (http://help.devexpress.com/#XtraCharts/DevExpressXtraChartsCrosshairOptions_ShowValueLabelstopic)
// and CrosshairOptions.ShowValueLine
// (http://help.devexpress.com/#XtraCharts/DevExpressXtraChartsCrosshairOptions_ShowValueLinetopic)
// properties to true. Note that the customization of the crosshair cursor is
// provided for the CrosshairOptions.SnapMode
// (http://documentation.devexpress.com/#XtraCharts/DevExpressXtraChartsCrosshairOptions_SnapModetopic)
// property set to NearestArgument.
// 
// You can find sample updates and versions for different programming languages here:
// http://www.devexpress.com/example=E4307

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomDrawCrosshairCursor.Properties {


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
    }
}
